### ISSUE TITLE
如何修改键盘的布局？

### ISSUE THREAD

**Issue by BenBeng** [shicang1990/SCNumberKeyBoard#10]
比如说去掉小数点这种的？

**Comment by RockerHX** [comment]
打开工程，工程目录`SCNumberKeyBoard -> Xib -> SCNumberKeyBoard.xib`，修改此布局文件即可。
修改完成选择第二个`target`编译，编译成功后`Products`文件下`SCNumberKeyBoard.bundle`文件字体颜色会有红变黑，右键`Show in Finder`，把编译好的`SCNumberKeyBoard.bundle`替换掉`Resources`目录下的`bundle`文件即可。

题外话，问问为啥要去掉小数点，你只想要整倍金额输入吗？做这个键盘就是为了控制金额输入，其他需求这个键盘满足不了哈
