### ISSUE TITLE
Where can I change the symbol to text 'Done'

### ISSUE THREAD

**Issue by sebasdeweert** [shicang1990/SCNumberKeyBoard#2]
Thank you for this framework! :+1: 

I was wondering where I can change the symbol (http://i59.tinypic.com/23h0i7p_th.png)  to text like 'Done' ?!

**Comment by RockerHX** [comment]
Sorry, I forgot add localization, you can change "确定" to "done" on xib and  I will add localization

**Comment by sebasdeweert** [comment]
Thanks! :)

If I change the "确定" to "done" (http://oi59.tinypic.com/2niv1it.jpg)  in the SCNumberKeyBoard.xib the text doesn't display.

**Comment by RockerHX** [comment]
That's first step only!
Next step, you should tap scheme and change the target from "SCNumberKeyBoardDemo" to the bundle of "SCNumberKeyBoard", device chose "IOS Devices".
Then run once, and open the "Products" folder, the "SCNumberKeyBoard.bundle" file's color will change from red to black.
Selceted "SCNumberKeyBoard.bundle" file and Right-click, and take the "SCNumberKeyBoard.bundle" overwrite the "SCNumberKeyBoard.bundle" that on the "Resources" folder.

**Comment by sebasdeweert** [comment]
Thanks!!! It works! :+1: :+1:

**Comment by sebasdeweert** [comment]
I send you an email with a problem I discovered...

**Comment by jordanform** [comment]
Hi, Great work. If i use it by cocoapod. There is no xib file in it. How do I change the 確定 button title.
I try to modify it in function "keyBoardView" and add a line [self.enterButton setTitle:@"Enter" forState:UIControlStateNormal]; but no work at all.

Never mind, I modify here and it work.
- (void)initConfig
  {
  _numbers = @[].mutableCopy;
  [_enterButton setTitle:@"Done" forState:UIControlStateNormal];
  }

**Comment by RockerHX** [comment]
Thank you:+1: :+1: @jordanform 
I will test and try open a new api to change title of "enter" button
