### ISSUE TITLE
#crash running in bundlePath error and missing file include who unuse CocoaPods

### ISSUE THREAD

**Issue by vbonluk** [shicang1990/SCNumberKeyBoard#5]
将SCNumberKeyBoardDemo/Classes文件夹中的所有文件拽入项目中
导入主头文件：#import "SCNumberKeyBoard.h"

Issues 1:
前面的只是针对CocoaPods的导入。
上面列出的“将SCNumberKeyBoardDemo/Classes文件夹中的所有文件拽入项目中”
我按照你的步骤来做，却crash了。
最后找到了原因是：你的xib文件在另外一个名为SCNumberKeyBoard的文件夹。不在class里面。

Issues 2:
导入两个进去后，发现还是crash。
经过断点调试，找到了原因来自：

// Init keyboard view by xib
    NSURL *bundleURL = [[NSBundle mainBundle] URLForResource:@"SCNumberKeyBoard" withExtension:@"bundle"];
    NSBundle *bundle = [NSBundle bundleWithURL:bundleURL];
    self = [[bundle loadNibNamed:@"SCNumberKeyBoard" owner:self options:nil] firstObject];

修改为：
    // Init keyboard view by xib
    NSBundle *bundle = [NSBundle mainBundle];
    self = [[bundle loadNibNamed:@"SCNumberKeyBoard" owner:self options:nil] firstObject];

后方可正常使用。

Last：
        建议将所有有用的包都放一个地方。因为有的项目并不使用CocoaPods，需要手动导入。如果不放统一包里面，又没有说明，会有问题。其次那个路径问题应该也是导致的。

最后来一句：支持国产!

**Comment by RockerHX** [comment]
## 谢谢支持~

在使用文档描述上这个失误太大了，我从我另外个项目上复制粘贴的问题，那个项目没有资源文件，唉唉，错不该，万恶的复制粘贴。

如果是直接拖拽的资源文件进入工程，那就只能用

``` objc
// Init keyboard view by xib
NSBundle *bundle = [NSBundle mainBundle];
self = [[bundle loadNibNamed:@"SCNumberKeyBoard" owner:self options:nil] firstObject];
```

这种方式来加载。

我代码里的是资源文件经过编译后加载方式。
我稍后把文档给修正一下，谢谢
