### ISSUE TITLE
#UITextField delegate method not called normal

### ISSUE THREAD

**Issue by vbonluk** [shicang1990/SCNumberKeyBoard#6]
使用了
[SCNumberKeyBoard showWithTextField:self.inputMoney enter:^(UITextField *textField, NSString *number) {
        NSLog(@"textField:%@ - number:%@", textField, number);
        if ([self.inputMoney.text floatValue] > [self.moneyMax.text floatValue]) {
            NSLog(@"数额大了");
        }
    } close:^(UITextField *textField, NSString *number) {
        NSLog(@"textField:%@ - number:%@", textField, number);
    }];

方法来添加后，发现UITextField的delegate方法：
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string{}
  不能被正常调用了。

**Comment by RockerHX** [comment]
这个问题确实存在，最开始设计的时候忘了处理，现在代理方法只能响应

``` objc
- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField;
- (void)textFieldDidBeginEditing:(UITextField *)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField *)textField;
- (void)textFieldDidEndEditing:(UITextField *)textField;
- (BOOL)textFieldShouldClear:(UITextField *)textField
```

其他的我下个版本做相应支持，谢谢
但是`- (BOOL)textFieldShouldClear:(UITextField *)textField`稍微还有点问题，正在调试解决
