### ISSUE TITLE
#UITextField delegate method called success,but it work have something wrong in return value

### ISSUE THREAD

**Issue by vbonluk** [shicang1990/SCNumberKeyBoard#7]
In one word:

UITextField delegate method:
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
  
  I try to do someting limited to user input when they input number.
  if they input number out of rang I wanna to return NO value to stop input.
  but it doesn't work.

**Comment by RockerHX** [comment]
OK, I will fix it.

I want to know what you going to do?
