### ISSUE TITLE
textfield text 错误

### ISSUE THREAD

**Issue by markrookie** [shicang1990/SCNumberKeyBoard#9]
每次点了确定键盘隐藏，紧接着再点textfield继续输入，为什么上次输入的内容还在，即使把textfield设置内容设置为空，如果在Block里面把返回的textfield设置为空，那么textfield输入的内容就再也不会显示

**Comment by RockerHX** [comment]
上述表现很正常，没有什么问题啊，系统的`textfield`也是重新点击继续输入，也没有重新点击清空内容。这个金额输入键盘只是利用了一些小伎俩在实现，`textfield.text`的值和显示的值唯一的关联就是只负责显示，我测试了，设置`text`可以正常显示，还有你在`block`里把`textfield`设置为空就切断了其与`SCNumberKeyBoard`之间的引用，将其不再受`SCNumberKeyBoard`控制，肯定就会想你描述的这样。
